BEGIN;

TRUNCATE TABLE financial_audit_events RESTART IDENTITY CASCADE;
TRUNCATE TABLE financial_transfers RESTART IDENTITY CASCADE;
TRUNCATE TABLE financial_entries RESTART IDENTITY CASCADE;

COMMIT;
